name: Publish Chrome Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build extension
        run: npm run build
      
      - name: Create zip file
        run: |
          cd dist
          zip -r ../extension.zip ./*
          cd ..
      
      - name: Upload & Publish to Chrome Web Store
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: extension.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.WEBSTORE_REFRESH_TOKEN }}
          publish: true
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: extension-zip
          path: extension.zip
          retention-days: 5
